-- MySQL Script generated by MySQL Workbench
-- Thu Jan 12 09:35:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projectpaymybuddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectpaymybuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectpaymybuddy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projectpaymybuddy` ;

-- -----------------------------------------------------
-- Table `projectpaymybuddy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectpaymybuddy`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `wallet` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectpaymybuddy`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectpaymybuddy`.`bank_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iban` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK92iik4jwhk7q385jubl2bc2mm` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK92iik4jwhk7q385jubl2bc2mm`
    FOREIGN KEY (`user_id`)
    REFERENCES `projectpaymybuddy`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectpaymybuddy`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectpaymybuddy`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `cost` FLOAT NULL DEFAULT NULL,
  `date` DATETIME(6) NULL DEFAULT NULL,
  `fee` FLOAT NULL DEFAULT NULL,
  `contact_user_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `contact_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `FKs0x2wktm13lqynhb3isutuh1p` (`contact_user_id` ASC) VISIBLE,
  INDEX `FKsg7jp0aj6qipr50856wf6vbw1` (`user_id` ASC) VISIBLE,
  INDEX `FKl3qe98lomhtjncvkr3u3uhvh1` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `FKl3qe98lomhtjncvkr3u3uhvh1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `projectpaymybuddy`.`user` (`user_id`),
  CONSTRAINT `FKs0x2wktm13lqynhb3isutuh1p`
    FOREIGN KEY (`contact_user_id`)
    REFERENCES `projectpaymybuddy`.`user` (`user_id`),
  CONSTRAINT `FKsg7jp0aj6qipr50856wf6vbw1`
    FOREIGN KEY (`user_id`)
    REFERENCES `projectpaymybuddy`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectpaymybuddy`.`transaction_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectpaymybuddy`.`transaction_bank` (
  `transaction_bank_id` INT NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NULL DEFAULT NULL,
  `in_time` DATETIME(6) NULL DEFAULT NULL,
  `operation_type` VARCHAR(255) NULL DEFAULT NULL,
  `bankaccount_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_bank_id`),
  INDEX `FK4xb2p4f94o2vyndm6l24mmvwk` (`bankaccount_id` ASC) VISIBLE,
  INDEX `FKit43deq8hwse3sws3twu4j4i` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK4xb2p4f94o2vyndm6l24mmvwk`
    FOREIGN KEY (`bankaccount_id`)
    REFERENCES `projectpaymybuddy`.`bank_account` (`id`),
  CONSTRAINT `FKit43deq8hwse3sws3twu4j4i`
    FOREIGN KEY (`user_id`)
    REFERENCES `projectpaymybuddy`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectpaymybuddy`.`user_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectpaymybuddy`.`user_contacts` (
  `user_user_id` INT NOT NULL,
  `contacts_user_id` INT NOT NULL,
  UNIQUE INDEX `UK_5u0cheolvmxbcajaerxxhpjdf` (`contacts_user_id` ASC) VISIBLE,
  INDEX `FKe365y1axdfcsyl6d6k3x49p6` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `FK6aq977u9wai48hvsvnudmc8e4`
    FOREIGN KEY (`contacts_user_id`)
    REFERENCES `projectpaymybuddy`.`user` (`user_id`),
  CONSTRAINT `FKe365y1axdfcsyl6d6k3x49p6`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `projectpaymybuddy`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
